// <auto-generated />
using System;
using GianssWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GianssWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GianssWebApi.Models.Gian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.Property<DateTime>("UptdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Gians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            CreationDate = new DateTime(2024, 2, 5, 17, 46, 36, 862, DateTimeKind.Local).AddTicks(35),
                            Detalle = "Detalle Test 1",
                            ImagenUrl = "",
                            MetrosCuadrados = 60,
                            Name = "Test1",
                            Ocupantes = 5,
                            Tarifa = 600.0,
                            UptdateDate = new DateTime(2024, 2, 5, 17, 46, 36, 862, DateTimeKind.Local).AddTicks(47)
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            CreationDate = new DateTime(2024, 2, 5, 17, 46, 36, 862, DateTimeKind.Local).AddTicks(49),
                            Detalle = "Detalle Test 2",
                            ImagenUrl = "",
                            MetrosCuadrados = 160,
                            Name = "Test2",
                            Ocupantes = 10,
                            Tarifa = 800.0,
                            UptdateDate = new DateTime(2024, 2, 5, 17, 46, 36, 862, DateTimeKind.Local).AddTicks(50)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
